module Demo.Startpage.Svg.Checkbox exposing (view)

import Html exposing (Html)
import Svg exposing (defs, desc, g, mask, path, rect, svg, text, title, use)
import Svg.Attributes exposing (d, fill, fillRule, height, id, opacity, stroke, strokeWidth, transform, version, viewBox, width, x, xlinkHref, y)


view : Html msg
view =
    svg [ viewBox "0 0 180 180", version "1.1" ]
        [ title []
            [ text "checkbox_180px " ]
        , desc []
            [ text "Created with Sketch." ]
        , defs []
            [ rect [ id "__1e_NOcu__path-1", x "0", y "0", width "180", height "180" ]
                []
            , path [ d "M19,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.11,21 21,20.1 21,19 L21,5 C21,3.9 20.11,3 19,3 Z M10,17 L5,12 L6.41,10.59 L10,14.17 L17.59,6.58 L19,8 L10,17 Z", id "__1e_NOcu__path-3" ]
                []
            , path [ d "M19,5 L19,19 L5,19 L5,5 L19,5 Z M19,3 L5,3 C3.9,3 3,3.9 3,5 L3,19 C3,20.1 3.9,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,5 C21,3.9 20.1,3 19,3 Z", id "__1e_NOcu__path-5" ]
                []
            , path [ d "M19,5 L19,19 L5,19 L5,5 L19,5 Z M19,3 L5,3 C3.9,3 3,3.9 3,5 L3,19 C3,20.1 3.9,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,5 C21,3.9 20.1,3 19,3 Z", id "__1e_NOcu__path-7" ]
                []
            , path [ d "M19,5 L19,19 L5,19 L5,5 L19,5 Z M19,3 L5,3 C3.9,3 3,3.9 3,5 L3,19 C3,20.1 3.9,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,5 C21,3.9 20.1,3 19,3 Z", id "__1e_NOcu__path-9" ]
                []
            ]
        , g [ id "__1e_NOcu__checkbox_180px-", stroke "none", strokeWidth "1", fill "none", fillRule "evenodd" ]
            [ g [ id "__1e_NOcu__Dialog-/-Header-Copy-19" ]
                [ mask [ id "__1e_NOcu__mask-2", fill "white" ]
                    [ use [ xlinkHref "#__1e_NOcu__path-1" ]
                        []
                    ]
                , use [ id "__1e_NOcu__Mask", fill "#FAFAFA", xlinkHref "#__1e_NOcu__path-1" ]
                    []
                , g [ id "__1e_NOcu__Selection-Control-/-Checkbox-/-On-/-Enabled", Svg.Attributes.mask "url(#__1e_NOcu__mask-2)" ]
                    [ g [ transform "translate(78.000000, 27.000000)", id "__1e_NOcu__Icon-/-Toggle-/-Checkbox-/-Fill" ]
                        [ g []
                            [ mask [ id "__1e_NOcu__mask-4", fill "white" ]
                                [ use [ xlinkHref "#__1e_NOcu__path-3" ]
                                    []
                                ]
                            , g [ id "__1e_NOcu__ic_check_box_24px", fillRule "nonzero" ]
                                []
                            , g [ id "__1e_NOcu__?-/-Color-/-Icons-/-Primary-or-Secondary", Svg.Attributes.mask "url(#__1e_NOcu__mask-4)", fill "#212121", fillRule "evenodd" ]
                                [ g [ id "__1e_NOcu__?-/-Color-/-Primary-/-Main" ]
                                    [ g [ id "__1e_NOcu__?-/-Color-/-Primary-/-900" ]
                                        [ rect [ id "__1e_NOcu__Rectangle-13", x "0", y "0", width "24", height "24" ]
                                            []
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                , g [ id "__1e_NOcu__Selection-Control-/-Checkbox-/-Off-/-Enabled", Svg.Attributes.mask "url(#__1e_NOcu__mask-2)" ]
                    [ g [ transform "translate(78.000000, 61.000000)", id "__1e_NOcu__Icon-/-Toggle-/-Checkbox-Outline-/-Fill" ]
                        [ g []
                            [ mask [ id "__1e_NOcu__mask-6", fill "white" ]
                                [ use [ xlinkHref "#__1e_NOcu__path-5" ]
                                    []
                                ]
                            , g [ id "__1e_NOcu__ic_check_box_outline_blank_24px", fillRule "nonzero" ]
                                []
                            , g [ id "__1e_NOcu__?-/-Color-/-Icons-/-Black-/-Inactive", Svg.Attributes.mask "url(#__1e_NOcu__mask-6)", fill "#000000", fillRule "evenodd", opacity "0.54" ]
                                [ rect [ id "__1e_NOcu__Rectangle", x "0", y "0", width "24", height "24" ]
                                    []
                                ]
                            ]
                        ]
                    ]
                , g [ id "__1e_NOcu__Selection-Control-/-Checkbox-/-Off-/-Enabled", Svg.Attributes.mask "url(#__1e_NOcu__mask-2)" ]
                    [ g [ transform "translate(78.000000, 95.000000)", id "__1e_NOcu__Icon-/-Toggle-/-Checkbox-Outline-/-Fill" ]
                        [ g []
                            [ mask [ id "__1e_NOcu__mask-8", fill "white" ]
                                [ use [ xlinkHref "#__1e_NOcu__path-7" ]
                                    []
                                ]
                            , g [ id "__1e_NOcu__ic_check_box_outline_blank_24px", fillRule "nonzero" ]
                                []
                            , g [ id "__1e_NOcu__?-/-Color-/-Icons-/-Black-/-Inactive", Svg.Attributes.mask "url(#__1e_NOcu__mask-8)", fill "#000000", fillRule "evenodd", opacity "0.54" ]
                                [ rect [ id "__1e_NOcu__Rectangle", x "0", y "0", width "24", height "24" ]
                                    []
                                ]
                            ]
                        ]
                    ]
                , g [ id "__1e_NOcu__Selection-Control-/-Checkbox-/-Off-/-Enabled", Svg.Attributes.mask "url(#__1e_NOcu__mask-2)" ]
                    [ g [ transform "translate(78.000000, 129.000000)", id "__1e_NOcu__Icon-/-Toggle-/-Checkbox-Outline-/-Fill" ]
                        [ g []
                            [ mask [ id "__1e_NOcu__mask-10", fill "white" ]
                                [ use [ xlinkHref "#__1e_NOcu__path-9" ]
                                    []
                                ]
                            , g [ id "__1e_NOcu__ic_check_box_outline_blank_24px", fillRule "nonzero" ]
                                []
                            , g [ id "__1e_NOcu__?-/-Color-/-Icons-/-Black-/-Inactive", Svg.Attributes.mask "url(#__1e_NOcu__mask-10)", fill "#000000", fillRule "evenodd", opacity "0.54" ]
                                [ rect [ id "__1e_NOcu__Rectangle", x "0", y "0", width "24", height "24" ]
                                    []
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
