module Demo.Startpage.Svg.Dialog exposing (view)

import Html exposing (Html)
import Svg exposing (defs, desc, feColorMatrix, feGaussianBlur, feMerge, feMergeNode, feOffset, filter, g, mask, path, rect, svg, text, text_, title, tspan, use)
import Svg.Attributes exposing (d, dx, dy, fill, fillOpacity, fillRule, filterUnits, fontFamily, fontSize, fontWeight, height, id, in_, letterSpacing, opacity, result, stdDeviation, stroke, strokeWidth, transform, type_, values, version, viewBox, width, x, xlinkHref, y)


view : Html msg
view =
    svg [ viewBox "0 0 180 180", version "1.1" ]
        [ title []
            [ text "dialog_180px" ]
        , desc []
            [ text "Created with Sketch." ]
        , defs []
            [ rect [ id "__HcfKmG2__path-1", x "0", y "0", width "180", height "180" ]
                []
            , rect [ id "__HcfKmG2__path-3", x "0", y "0", width "180", height "180" ]
                []
            , path [ d "M2.58585859,0 L87.9191919,0 C89.3473222,-2.62343273e-16 90.5050505,1.15772832 90.5050505,2.58585859 L90.5050505,77.5757576 C90.5050505,79.0038878 89.3473222,80.1616162 87.9191919,80.1616162 L2.58585859,80.1616162 C1.15772832,80.1616162 1.95125235e-15,79.0038878 1.77635684e-15,77.5757576 L0,2.58585859 C-1.74895515e-16,1.15772832 1.15772832,-5.06672725e-15 2.58585859,-5.32907052e-15 Z", id "__HcfKmG2__path-5" ]
                []
            , filter [ x "-8.3%", y "-6.9%", width "116.6%", height "118.7%", filterUnits "objectBoundingBox", id "__HcfKmG2__filter-7" ]
                [ feOffset [ dx "0", dy "0", in_ "SourceAlpha", result "shadowOffsetOuter1" ]
                    []
                , feGaussianBlur [ stdDeviation "1.5", in_ "shadowOffsetOuter1", result "shadowBlurOuter1" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.2 0", type_ "matrix", in_ "shadowBlurOuter1", result "shadowMatrixOuter1" ]
                    []
                , feOffset [ dx "0", dy "1", in_ "SourceAlpha", result "shadowOffsetOuter2" ]
                    []
                , feGaussianBlur [ stdDeviation "1", in_ "shadowOffsetOuter2", result "shadowBlurOuter2" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.12 0", type_ "matrix", in_ "shadowBlurOuter2", result "shadowMatrixOuter2" ]
                    []
                , feOffset [ dx "0", dy "1", in_ "SourceAlpha", result "shadowOffsetOuter3" ]
                    []
                , feGaussianBlur [ stdDeviation "0.5", in_ "shadowOffsetOuter3", result "shadowBlurOuter3" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.14 0", type_ "matrix", in_ "shadowBlurOuter3", result "shadowMatrixOuter3" ]
                    []
                , feMerge []
                    [ feMergeNode [ in_ "shadowMatrixOuter1" ]
                        []
                    , feMergeNode [ in_ "shadowMatrixOuter2" ]
                        []
                    , feMergeNode [ in_ "shadowMatrixOuter3" ]
                        []
                    ]
                ]
            ]
        , g [ id "__HcfKmG2__dialog_180px", stroke "none", strokeWidth "1", fill "none", fillRule "evenodd" ]
            [ g [ id "__HcfKmG2__Group" ]
                [ mask [ id "__HcfKmG2__mask-2", fill "white" ]
                    [ use [ xlinkHref "#__HcfKmG2__path-1" ]
                        []
                    ]
                , use [ id "__HcfKmG2__Mask", fill "#FAFAFA", xlinkHref "#__HcfKmG2__path-1" ]
                    []
                , g [ Svg.Attributes.mask "url(#__HcfKmG2__mask-2)" ]
                    [ g [ id "__HcfKmG2__Image-Treatments-/-Tonal-/-Black", opacity "0.5" ]
                        [ mask [ id "__HcfKmG2__mask-4", fill "white" ]
                            [ use [ xlinkHref "#__HcfKmG2__path-3" ]
                                []
                            ]
                        , use [ id "__HcfKmG2__Surface", fill "#000000", fillRule "evenodd", opacity "0.32", xlinkHref "#__HcfKmG2__path-3" ]
                            []
                        ]
                    , g [ id "__HcfKmG2__Dialogs-/-Simple-/-with-Header", transform "translate(45.000000, 46.000000)" ]
                        [ mask [ id "__HcfKmG2__mask-6", fill "white" ]
                            [ use [ xlinkHref "#__HcfKmG2__path-5" ]
                                []
                            ]
                        , g [ id "__HcfKmG2__Surface" ]
                            [ use [ fill "black", fillOpacity "1", Svg.Attributes.filter "url(#__HcfKmG2__filter-7)", xlinkHref "#__HcfKmG2__path-5" ]
                                []
                            , use [ fill "#FAFAFA", fillRule "evenodd", xlinkHref "#__HcfKmG2__path-5" ]
                                []
                            ]
                        , g [ id "__HcfKmG2__?-/-Color-/-Background-/-Light", Svg.Attributes.mask "url(#__HcfKmG2__mask-6)", fill "#FFFFFF", fillRule "evenodd" ]
                            [ rect [ id "__HcfKmG2__Rectangle-13", x "0", y "0", width "91.9191919", height "80.8080808" ]
                                []
                            ]
                        , g [ id "__HcfKmG2__Text-/-Subtitle-1-/-Background-/-Left", opacity "0.54", Svg.Attributes.mask "url(#__HcfKmG2__mask-6)", fillOpacity "0.87", fontFamily "Roboto-Regular, Roboto", fontSize "5.17171717", fontWeight "normal", letterSpacing "0.0484848504" ]
                            [ g [ transform "translate(7.757576, 19.070707)", id "__HcfKmG2__Subtitle-1", opacity "0.87" ]
                                [ text_ []
                                    [ tspan [ x "0", y "5", fill "#000000" ]
                                        [ text "Lorem ipsum dolor sit amet, " ]
                                    , tspan [ x "0", y "12.7575758", fill "#000000" ]
                                        [ text "consectetur adipisicing elit, sed " ]
                                    , tspan [ x "0", y "20.5151515", fill "#000000" ]
                                        [ text "do eiusmod tempor incididunt " ]
                                    , tspan [ x "0", y "28.2727273", fill "#000000" ]
                                        [ text "ut labore et dolore magna wirl " ]
                                    , tspan [ x "0", y "36.030303", fill "#000000" ]
                                        [ text "aliqua. Up exlaborum incididunt" ]
                                    ]
                                ]
                            ]
                        , g [ id "__HcfKmG2__Text-/-H6-/-Background-/-Left", Svg.Attributes.mask "url(#__HcfKmG2__mask-6)", fillOpacity "0.87", fontFamily "Roboto-Medium, Roboto", fontSize "6.46464646", fontWeight "400", letterSpacing "0.0484848504", opacity "0.87" ]
                            [ g [ transform "translate(7.757576, 6.787879)", id "__HcfKmG2__Headline-6" ]
                                [ text_ []
                                    [ tspan [ x "0", y "6", fill "#000000" ]
                                        [ text "Dialog Header" ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
