module Demo.Startpage.Svg.Drawer exposing (view)

import Html exposing (Html)
import Svg exposing (defs, desc, feColorMatrix, feGaussianBlur, feMerge, feMergeNode, feMorphology, feOffset, filter, g, mask, rect, svg, text, title, use)
import Svg.Attributes exposing (dx, dy, fill, fillOpacity, fillRule, filterUnits, height, id, in_, operator, radius, result, stdDeviation, stroke, strokeWidth, type_, values, version, viewBox, width, x, xlinkHref, y)


view : Html msg
view =
    svg [ viewBox "0 0 180 180", version "1.1" ]
        [ title []
            [ text "drawer_180px" ]
        , desc []
            [ text "Created with Sketch." ]
        , defs []
            [ rect [ id "__2GuaX38__path-1", x "0", y "0", width "180", height "180" ]
                []
            , rect [ id "__2GuaX38__path-3", x "0", y "0", width "180", height "180" ]
                []
            , rect [ id "__2GuaX38__path-5", x "0", y "0", width "136", height "180" ]
                []
            , filter [ x "-34.2%", y "-17.5%", width "168.4%", height "151.7%", filterUnits "objectBoundingBox", id "__2GuaX38__filter-7" ]
                [ feOffset [ dx "0", dy "4", in_ "SourceAlpha", result "shadowOffsetOuter1" ]
                    []
                , feGaussianBlur [ stdDeviation "2.5", in_ "shadowOffsetOuter1", result "shadowBlurOuter1" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.2 0", type_ "matrix", in_ "shadowBlurOuter1", result "shadowMatrixOuter1" ]
                    []
                , feMorphology [ radius "1.5", operator "dilate", in_ "SourceAlpha", result "shadowSpreadOuter2" ]
                    []
                , feOffset [ dx "0", dy "3", in_ "shadowSpreadOuter2", result "shadowOffsetOuter2" ]
                    []
                , feGaussianBlur [ stdDeviation "7.5", in_ "shadowOffsetOuter2", result "shadowBlurOuter2" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.12 0", type_ "matrix", in_ "shadowBlurOuter2", result "shadowMatrixOuter2" ]
                    []
                , feMorphology [ radius "0.5", operator "dilate", in_ "SourceAlpha", result "shadowSpreadOuter3" ]
                    []
                , feOffset [ dx "0", dy "8", in_ "shadowSpreadOuter3", result "shadowOffsetOuter3" ]
                    []
                , feGaussianBlur [ stdDeviation "6", in_ "shadowOffsetOuter3", result "shadowBlurOuter3" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.14 0", type_ "matrix", in_ "shadowBlurOuter3", result "shadowMatrixOuter3" ]
                    []
                , feMerge []
                    [ feMergeNode [ in_ "shadowMatrixOuter1" ]
                        []
                    , feMergeNode [ in_ "shadowMatrixOuter2" ]
                        []
                    , feMergeNode [ in_ "shadowMatrixOuter3" ]
                        []
                    ]
                ]
            ]
        , g [ id "__2GuaX38__drawer_180px", stroke "none", strokeWidth "1", fill "none", fillRule "evenodd" ]
            [ g [ id "__2GuaX38__Scrim-+-Surface-Mask" ]
                [ mask [ id "__2GuaX38__mask-2", fill "white" ]
                    [ use [ xlinkHref "#__2GuaX38__path-1" ]
                        []
                    ]
                , use [ id "__2GuaX38__Mask", fill "#FAFAFA", xlinkHref "#__2GuaX38__path-1" ]
                    []
                , mask [ id "__2GuaX38__mask-4", fill "white" ]
                    [ use [ xlinkHref "#__2GuaX38__path-3" ]
                        []
                    ]
                , use [ id "__2GuaX38__Mask", fillOpacity "0.32", fill "#000000", xlinkHref "#__2GuaX38__path-3" ]
                    []
                , mask [ id "__2GuaX38__mask-6", fill "white" ]
                    [ use [ xlinkHref "#__2GuaX38__path-5" ]
                        []
                    ]
                , g [ id "__2GuaX38__Surface" ]
                    [ use [ fill "black", fillOpacity "1", Svg.Attributes.filter "url(#__2GuaX38__filter-7)", xlinkHref "#__2GuaX38__path-5" ]
                        []
                    , use [ fill "#FFFFFF", fillRule "evenodd", xlinkHref "#__2GuaX38__path-5" ]
                        []
                    ]
                ]
            ]
        ]
