module Demo.Startpage.Svg.Elevation exposing (view)

import Html exposing (Html)
import Svg exposing (defs, desc, feColorMatrix, feGaussianBlur, feMerge, feMergeNode, feMorphology, feOffset, filter, g, mask, rect, svg, text, title, use)
import Svg.Attributes exposing (dx, dy, fill, fillOpacity, fillRule, filterUnits, height, id, in_, operator, radius, result, rx, stdDeviation, stroke, strokeWidth, transform, type_, values, version, viewBox, width, x, xlinkHref, y)


view : Html msg
view =
    svg [ viewBox "0 0 180 180", version "1.1" ]
        [ title []
            [ text "elevation_180px" ]
        , desc []
            [ text "Created with Sketch." ]
        , defs []
            [ rect [ id "__2mGQ0lw__path-1", x "0", y "0", width "180", height "180" ]
                []
            , rect [ id "__2mGQ0lw__path-3", x "0", y "0", width "120", height "120", rx "2" ]
                []
            , filter [ x "-76.7%", y "-51.7%", width "253.3%", height "253.3%", filterUnits "objectBoundingBox", id "__2mGQ0lw__filter-4" ]
                [ feOffset [ dx "0", dy "8", in_ "SourceAlpha", result "shadowOffsetOuter1" ]
                    []
                , feGaussianBlur [ stdDeviation "5", in_ "shadowOffsetOuter1", result "shadowBlurOuter1" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.2 0", type_ "matrix", in_ "shadowBlurOuter1", result "shadowMatrixOuter1" ]
                    []
                , feMorphology [ radius "2.5", operator "dilate", in_ "SourceAlpha", result "shadowSpreadOuter2" ]
                    []
                , feOffset [ dx "0", dy "6", in_ "shadowSpreadOuter2", result "shadowOffsetOuter2" ]
                    []
                , feGaussianBlur [ stdDeviation "15", in_ "shadowOffsetOuter2", result "shadowBlurOuter2" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.12 0", type_ "matrix", in_ "shadowBlurOuter2", result "shadowMatrixOuter2" ]
                    []
                , feMorphology [ radius "1", operator "dilate", in_ "SourceAlpha", result "shadowSpreadOuter3" ]
                    []
                , feOffset [ dx "0", dy "16", in_ "shadowSpreadOuter3", result "shadowOffsetOuter3" ]
                    []
                , feGaussianBlur [ stdDeviation "12", in_ "shadowOffsetOuter3", result "shadowBlurOuter3" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.14 0", type_ "matrix", in_ "shadowBlurOuter3", result "shadowMatrixOuter3" ]
                    []
                , feMerge []
                    [ feMergeNode [ in_ "shadowMatrixOuter1" ]
                        []
                    , feMergeNode [ in_ "shadowMatrixOuter2" ]
                        []
                    , feMergeNode [ in_ "shadowMatrixOuter3" ]
                        []
                    ]
                ]
            ]
        , g [ id "__2mGQ0lw__elevation_180px", stroke "none", strokeWidth "1", fill "none", fillRule "evenodd" ]
            [ g [ id "__2mGQ0lw__Dialog-/-Header-Copy-23" ]
                [ mask [ id "__2mGQ0lw__mask-2", fill "white" ]
                    [ use [ xlinkHref "#__2mGQ0lw__path-1" ]
                        []
                    ]
                , use [ id "__2mGQ0lw__Mask", fill "#FAFAFA", xlinkHref "#__2mGQ0lw__path-1" ]
                    []
                , g [ Svg.Attributes.mask "url(#__2mGQ0lw__mask-2)", id "__2mGQ0lw__Shadow-/-16dp" ]
                    [ g [ transform "translate(30.000000, 30.000000)" ]
                        [ g []
                            [ g [ id "__2mGQ0lw__Rectangle" ]
                                [ use [ fill "black", fillOpacity "1", Svg.Attributes.filter "url(#__2mGQ0lw__filter-4)", xlinkHref "#__2mGQ0lw__path-3" ]
                                    []
                                , use [ fill "#FAFAFA", fillRule "evenodd", xlinkHref "#__2mGQ0lw__path-3" ]
                                    []
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
