module Demo.Startpage.Svg.Fab exposing (view)

import Html exposing (Html)
import Svg exposing (defs, desc, feColorMatrix, feGaussianBlur, feMerge, feMergeNode, feOffset, filter, g, mask, path, polygon, rect, svg, text, title, use)
import Svg.Attributes exposing (d, dx, dy, fill, fillOpacity, fillRule, filterUnits, height, id, in_, points, result, rx, stdDeviation, stroke, strokeWidth, style, transform, type_, values, version, viewBox, width, x, xlinkHref, y)


view : Html msg
view =
    svg [ viewBox "0 0 180 180", version "1.1", style "background: #FAFAFA;" ]
        [ title []
            [ text "floating_action_button_180px" ]
        , desc []
            [ text "Created with Sketch." ]
        , defs []
            [ rect [ id "__1Ff56XA__path-1", x "0", y "0", width "180", height "180" ]
                []
            , rect [ id "__1Ff56XA__path-3", x "0", y "0", width "56", height "56", rx "28" ]
                []
            , filter [ x "-43.8%", y "-31.2%", width "187.5%", height "187.5%", filterUnits "objectBoundingBox", id "__1Ff56XA__filter-5" ]
                [ feOffset [ dx "0", dy "1", in_ "SourceAlpha", result "shadowOffsetOuter1" ]
                    []
                , feGaussianBlur [ stdDeviation "5", in_ "shadowOffsetOuter1", result "shadowBlurOuter1" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.2 0", type_ "matrix", in_ "shadowBlurOuter1", result "shadowMatrixOuter1" ]
                    []
                , feOffset [ dx "0", dy "4", in_ "SourceAlpha", result "shadowOffsetOuter2" ]
                    []
                , feGaussianBlur [ stdDeviation "2.5", in_ "shadowOffsetOuter2", result "shadowBlurOuter2" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.12 0", type_ "matrix", in_ "shadowBlurOuter2", result "shadowMatrixOuter2" ]
                    []
                , feOffset [ dx "0", dy "2", in_ "SourceAlpha", result "shadowOffsetOuter3" ]
                    []
                , feGaussianBlur [ stdDeviation "2", in_ "shadowOffsetOuter3", result "shadowBlurOuter3" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.14 0", type_ "matrix", in_ "shadowBlurOuter3", result "shadowMatrixOuter3" ]
                    []
                , feMerge []
                    [ feMergeNode [ in_ "shadowMatrixOuter1" ]
                        []
                    , feMergeNode [ in_ "shadowMatrixOuter2" ]
                        []
                    , feMergeNode [ in_ "shadowMatrixOuter3" ]
                        []
                    ]
                ]
            , polygon [ id "__1Ff56XA__path-6", points "11 5 11 11 5 11 5 13 11 13 11 19 13 19 13 13 19 13 19 11 13 11 13 5" ]
                []
            , path [ d "M24,0 L114,0 C127.254834,-2.4348735e-15 138,10.745166 138,24 L138,24 C138,37.254834 127.254834,48 114,48 L24,48 C10.745166,48 1.623249e-15,37.254834 0,24 L0,24 C-1.623249e-15,10.745166 10.745166,2.4348735e-15 24,0 Z", id "__1Ff56XA__path-8" ]
                []
            , filter [ x "-6.5%", y "-12.5%", width "113.0%", height "137.5%", filterUnits "objectBoundingBox", id "__1Ff56XA__filter-10" ]
                [ feOffset [ dx "0", dy "1", in_ "SourceAlpha", result "shadowOffsetOuter1" ]
                    []
                , feGaussianBlur [ stdDeviation "1.5", in_ "shadowOffsetOuter1", result "shadowBlurOuter1" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.2 0", type_ "matrix", in_ "shadowBlurOuter1", result "shadowMatrixOuter1" ]
                    []
                , feOffset [ dx "0", dy "2", in_ "SourceAlpha", result "shadowOffsetOuter2" ]
                    []
                , feGaussianBlur [ stdDeviation "1", in_ "shadowOffsetOuter2", result "shadowBlurOuter2" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.12 0", type_ "matrix", in_ "shadowBlurOuter2", result "shadowMatrixOuter2" ]
                    []
                , feOffset [ dx "0", dy "0", in_ "SourceAlpha", result "shadowOffsetOuter3" ]
                    []
                , feGaussianBlur [ stdDeviation "1", in_ "shadowOffsetOuter3", result "shadowBlurOuter3" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.14 0", type_ "matrix", in_ "shadowBlurOuter3", result "shadowMatrixOuter3" ]
                    []
                , feMerge []
                    [ feMergeNode [ in_ "shadowMatrixOuter1" ]
                        []
                    , feMergeNode [ in_ "shadowMatrixOuter2" ]
                        []
                    , feMergeNode [ in_ "shadowMatrixOuter3" ]
                        []
                    ]
                ]
            , polygon [ id "__1Ff56XA__path-11", points "11 5 11 11 5 11 5 13 11 13 11 19 13 19 13 13 19 13 19 11 13 11 13 5" ]
                []
            ]
        , g [ id "__1Ff56XA__floating_action_button_180px", stroke "none", strokeWidth "1", fill "none", fillRule "evenodd" ]
            [ mask [ id "__1Ff56XA__mask-2", fill "white" ]
                [ use [ xlinkHref "#__1Ff56XA__path-1" ]
                    []
                ]
            , g [ id "__1Ff56XA__Mask" ]
                []
            , g [ id "__1Ff56XA__FAB-/-Standard-/-Circular-/-Enabled", Svg.Attributes.mask "url(#__1Ff56XA__mask-2)" ]
                [ g [ transform "translate(60.000000, 62.000000)" ]
                    [ mask [ id "__1Ff56XA__mask-4", fill "white" ]
                        [ use [ xlinkHref "#__1Ff56XA__path-3" ]
                            []
                        ]
                    , g [ id "__1Ff56XA__Surface", stroke "none", fill "none" ]
                        [ use [ fill "black", fillOpacity "1", Svg.Attributes.filter "url(#__1Ff56XA__filter-5)", xlinkHref "#__1Ff56XA__path-3" ]
                            []
                        , use [ fill "#FAFAFA", fillRule "evenodd", xlinkHref "#__1Ff56XA__path-3" ]
                            []
                        ]
                    , g [ id "__1Ff56XA__?-/-Color-/-Secondary-/-Main", stroke "none", fill "none", Svg.Attributes.mask "url(#__1Ff56XA__mask-4)", fillRule "evenodd" ]
                        [ g [ id "__1Ff56XA__?-/-Color-/-Primary-/-Main", fill "#212121" ]
                            [ g [ id "__1Ff56XA__?-/-Color-/-Primary-/-500" ]
                                [ rect [ id "__1Ff56XA__Rectangle-13", x "0", y "0", width "56", height "56" ]
                                    []
                                ]
                            ]
                        ]
                    , g [ id "__1Ff56XA__Icon-/-Add-/-Fill", stroke "none", fill "none", Svg.Attributes.mask "url(#__1Ff56XA__mask-4)" ]
                        [ g [ transform "translate(16.000000, 16.000000)" ]
                            [ mask [ id "__1Ff56XA__mask-7", fill "white" ]
                                [ use [ xlinkHref "#__1Ff56XA__path-6" ]
                                    []
                                ]
                            , g [ id "__1Ff56XA__Mask", stroke "none", fill "none" ]
                                []
                            , g [ id "__1Ff56XA__?-/-Color-/-Icons-/-White-/-Active", stroke "none", fill "none", Svg.Attributes.mask "url(#__1Ff56XA__mask-7)", fillRule "evenodd" ]
                                [ rect [ id "__1Ff56XA__Rectangle-13", fill "#FFFFFF", x "0", y "0", width "24", height "24" ]
                                    []
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
