module Demo.Startpage.Svg.Menu exposing (view)

import Html exposing (Html)
import Svg exposing (defs, desc, feColorMatrix, feGaussianBlur, feMerge, feMergeNode, feMorphology, feOffset, filter, g, mask, path, polygon, rect, svg, text, text_, title, tspan, use)
import Svg.Attributes exposing (d, dx, dy, fill, fillOpacity, fillRule, filterUnits, fontFamily, fontSize, fontWeight, height, id, in_, letterSpacing, opacity, operator, points, radius, result, rx, stdDeviation, stroke, strokeWidth, transform, type_, values, version, viewBox, width, x, xlinkHref, y)


view : Html msg
view =
    svg [ viewBox "0 0 180 180", version "1.1" ]
        [ title []
            [ text "menu_180px" ]
        , desc []
            [ text "Created with Sketch." ]
        , defs []
            [ rect [ id "__3bBWeS0__path-1", x "0", y "0", width "180", height "180" ]
                []
            , path [ d "M3.2,0 L99.2,0 C100.967311,-8.17308814e-15 102.4,1.4326888 102.4,3.2 L102.4,147.2 C102.4,148.967311 100.967311,150.4 99.2,150.4 L3.2,150.4 C1.4326888,150.4 2.88096846e-15,148.967311 2.66453526e-15,147.2 L4.4408921e-16,3.2 C2.27656009e-16,1.4326888 1.4326888,2.98918506e-15 3.2,2.66453526e-15 Z", id "__3bBWeS0__path-3" ]
                []
            , filter [ x "-32.7%", y "-15.0%", width "165.4%", height "144.5%", filterUnits "objectBoundingBox", id "__3bBWeS0__filter-5" ]
                [ feOffset [ dx "0", dy "3", in_ "SourceAlpha", result "shadowOffsetOuter1" ]
                    []
                , feGaussianBlur [ stdDeviation "2", in_ "shadowOffsetOuter1", result "shadowBlurOuter1" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.2 0", type_ "matrix", in_ "shadowBlurOuter1", result "shadowMatrixOuter1" ]
                    []
                , feMorphology [ radius "1", operator "dilate", in_ "SourceAlpha", result "shadowSpreadOuter2" ]
                    []
                , feOffset [ dx "0", dy "2", in_ "shadowSpreadOuter2", result "shadowOffsetOuter2" ]
                    []
                , feGaussianBlur [ stdDeviation "5.5", in_ "shadowOffsetOuter2", result "shadowBlurOuter2" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.12 0", type_ "matrix", in_ "shadowBlurOuter2", result "shadowMatrixOuter2" ]
                    []
                , feMorphology [ radius "0.5", operator "dilate", in_ "SourceAlpha", result "shadowSpreadOuter3" ]
                    []
                , feOffset [ dx "0", dy "6", in_ "shadowSpreadOuter3", result "shadowOffsetOuter3" ]
                    []
                , feGaussianBlur [ stdDeviation "4", in_ "shadowOffsetOuter3", result "shadowBlurOuter3" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.14 0", type_ "matrix", in_ "shadowBlurOuter3", result "shadowMatrixOuter3" ]
                    []
                , feMerge []
                    [ feMergeNode [ in_ "shadowMatrixOuter1" ]
                        []
                    , feMergeNode [ in_ "shadowMatrixOuter2" ]
                        []
                    , feMergeNode [ in_ "shadowMatrixOuter3" ]
                        []
                    ]
                ]
            , path [ d "M3.2,0 L99.2,0 C100.967311,-8.17308814e-15 102.4,1.4326888 102.4,3.2 L102.4,112 C102.4,113.767311 100.967311,115.2 99.2,115.2 L3.2,115.2 C1.4326888,115.2 1.02853176e-14,113.767311 2.22044605e-15,112 L4.4408921e-16,3.2 C2.27656009e-16,1.4326888 1.4326888,2.54509585e-15 3.2,2.22044605e-15 Z", id "__3bBWeS0__path-6" ]
                []
            , filter [ x "-32.7%", y "-19.5%", width "165.4%", height "158.2%", filterUnits "objectBoundingBox", id "__3bBWeS0__filter-8" ]
                [ feOffset [ dx "0", dy "3", in_ "SourceAlpha", result "shadowOffsetOuter1" ]
                    []
                , feGaussianBlur [ stdDeviation "2", in_ "shadowOffsetOuter1", result "shadowBlurOuter1" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.2 0", type_ "matrix", in_ "shadowBlurOuter1", result "shadowMatrixOuter1" ]
                    []
                , feMorphology [ radius "1", operator "dilate", in_ "SourceAlpha", result "shadowSpreadOuter2" ]
                    []
                , feOffset [ dx "0", dy "2", in_ "shadowSpreadOuter2", result "shadowOffsetOuter2" ]
                    []
                , feGaussianBlur [ stdDeviation "5.5", in_ "shadowOffsetOuter2", result "shadowBlurOuter2" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.12 0", type_ "matrix", in_ "shadowBlurOuter2", result "shadowMatrixOuter2" ]
                    []
                , feMorphology [ radius "0.5", operator "dilate", in_ "SourceAlpha", result "shadowSpreadOuter3" ]
                    []
                , feOffset [ dx "0", dy "6", in_ "shadowSpreadOuter3", result "shadowOffsetOuter3" ]
                    []
                , feGaussianBlur [ stdDeviation "4", in_ "shadowOffsetOuter3", result "shadowBlurOuter3" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.14 0", type_ "matrix", in_ "shadowBlurOuter3", result "shadowMatrixOuter3" ]
                    []
                , feMerge []
                    [ feMergeNode [ in_ "shadowMatrixOuter1" ]
                        []
                    , feMergeNode [ in_ "shadowMatrixOuter2" ]
                        []
                    , feMergeNode [ in_ "shadowMatrixOuter3" ]
                        []
                    ]
                ]
            , path [ d "M0.8,0 L114.2,0 C114.641828,7.76727589e-15 115,0.3581722 115,0.8 L115,25.0206897 C115,25.4625175 114.641828,25.8206897 114.2,25.8206897 L0.8,25.8206897 C0.3581722,25.8206897 -2.94349387e-15,25.4625175 -2.99760217e-15,25.0206897 L1.11022302e-16,0.8 C5.69140024e-17,0.3581722 0.3581722,7.47296265e-16 0.8,6.66133815e-16 Z", id "__3bBWeS0__path-9" ]
                []
            , rect [ id "__3bBWeS0__path-11", x "0", y "0", width "115", height "25.8206897", rx "0.8" ]
                []
            , rect [ id "__3bBWeS0__path-13", x "0", y "0", width "115", height "25.8206897", rx "0.8" ]
                []
            , rect [ id "__3bBWeS0__path-15", x "0", y "0", width "115", height "25.8206897", rx "0.8" ]
                []
            , polygon [ id "__3bBWeS0__path-17", points "7.6 14 11.6 10 7.6 6" ]
                []
            , rect [ id "__3bBWeS0__path-19", x "0", y "0", width "115", height "25.8206897", rx "0.8" ]
                []
            ]
        , g [ id "__3bBWeS0__menu_180px", stroke "none", strokeWidth "1", fill "none", fillRule "evenodd" ]
            [ g [ id "__3bBWeS0__Menu-/-Exposed" ]
                [ mask [ id "__3bBWeS0__mask-2", fill "white" ]
                    [ use [ xlinkHref "#__3bBWeS0__path-1" ]
                        []
                    ]
                , use [ id "__3bBWeS0__Mask", fill "#FAFAFA", xlinkHref "#__3bBWeS0__path-1" ]
                    []
                , g [ Svg.Attributes.mask "url(#__3bBWeS0__mask-2)" ]
                    [ g [ transform "translate(39.000000, 15.000000)" ]
                        [ mask [ id "__3bBWeS0__mask-4", fill "white" ]
                            [ use [ xlinkHref "#__3bBWeS0__path-3" ]
                                []
                            ]
                        , g [ id "__3bBWeS0__Surface", stroke "none", fill "none" ]
                            [ use [ fill "black", fillOpacity "1", Svg.Attributes.filter "url(#__3bBWeS0__filter-5)", xlinkHref "#__3bBWeS0__path-3" ]
                                []
                            , use [ fill "#FAFAFA", fillRule "evenodd", xlinkHref "#__3bBWeS0__path-3" ]
                                []
                            ]
                        , g [ id "__3bBWeS0__?-/-State-Overlay-/-Black-/-Selected", stroke "none", fill "none", Svg.Attributes.mask "url(#__3bBWeS0__mask-4)", fillRule "evenodd", opacity "0.08" ]
                            [ rect [ id "__3bBWeS0__Black-State-Overlay", fill "#000000", x "0", y "0", width "111.523404", height "149.361702" ]
                                []
                            ]
                        , g [ id "__3bBWeS0__Menu-/-Dropdown-/-Small", stroke "none", fill "none", Svg.Attributes.mask "url(#__3bBWeS0__mask-4)" ]
                            [ g [ transform "translate(0.000000, 35.200000)" ]
                                [ mask [ id "__3bBWeS0__mask-7", fill "white" ]
                                    [ use [ xlinkHref "#__3bBWeS0__path-6" ]
                                        []
                                    ]
                                , g [ id "__3bBWeS0__Surface", stroke "none", fill "none" ]
                                    [ use [ fill "black", fillOpacity "1", Svg.Attributes.filter "url(#__3bBWeS0__filter-8)", xlinkHref "#__3bBWeS0__path-6" ]
                                        []
                                    , use [ fill "#FAFAFA", fillRule "evenodd", xlinkHref "#__3bBWeS0__path-6" ]
                                        []
                                    ]
                                , g [ id "__3bBWeS0__?-/-Color-/-Surface-/-Light", stroke "none", fill "none", Svg.Attributes.mask "url(#__3bBWeS0__mask-7)", fillRule "evenodd" ]
                                    [ rect [ id "__3bBWeS0__Rectangle-13", fill "#FAFAFA", x "0", y "0", width "102", height "115" ]
                                        []
                                    ]
                                , g [ id "__3bBWeS0__List-/-Single-Line-/-Text-/-Body-2", stroke "none", fill "none", Svg.Attributes.mask "url(#__3bBWeS0__mask-7)" ]
                                    [ g [ transform "translate(-6.400000, 57.600000)" ]
                                        [ g [ id "__3bBWeS0__?-/-Text-/-Body-2-/-Selected-/-On-Surface-/-High-Emphasis-/-Left", transform "translate(12.800000, 4.631579)", fillOpacity "0.87", fontFamily "Roboto-Regular, Roboto", fontSize "11.2", fontWeight "normal", letterSpacing "0.2" ]
                                            [ text_ [ id "__3bBWeS0__Body-2", fill "#000000" ]
                                                [ tspan [ x "0", y "10" ]
                                                    [ text "Menu 3" ]
                                                ]
                                            ]
                                        , g [ id "__3bBWeS0__List-/-State-/-Selected" ]
                                            [ mask [ id "__3bBWeS0__mask-10", fill "white" ]
                                                [ use [ xlinkHref "#__3bBWeS0__path-9" ]
                                                    []
                                                ]
                                            , g [ id "__3bBWeS0__Surface" ]
                                                []
                                            , g [ id "__3bBWeS0__?-/-State-Overlay-/-Black-/-Selected", Svg.Attributes.mask "url(#__3bBWeS0__mask-10)", fill "#000000", fillRule "evenodd", opacity "0.08" ]
                                                [ rect [ id "__3bBWeS0__Black-State-Overlay", x "0", y "0", width "114.510638", height "25.8893617" ]
                                                    []
                                                ]
                                            ]
                                        ]
                                    ]
                                , g [ id "__3bBWeS0__List-/-Single-Line-/-Text-/-Body-2", stroke "none", fill "none", Svg.Attributes.mask "url(#__3bBWeS0__mask-7)" ]
                                    [ g [ transform "translate(-6.400000, 32.000000)" ]
                                        [ g [ id "__3bBWeS0__?-/-Text-/-Body-2-/-Selected-/-On-Surface-/-High-Emphasis-/-Left", transform "translate(12.800000, 4.631579)", fillOpacity "0.87", fontFamily "Roboto-Regular, Roboto", fontSize "11.2", fontWeight "normal", letterSpacing "0.2" ]
                                            [ text_ [ id "__3bBWeS0__Body-2", fill "#000000" ]
                                                [ tspan [ x "0", y "10" ]
                                                    [ text "Menu 2" ]
                                                ]
                                            ]
                                        , g [ id "__3bBWeS0__List-/-State-/-Resting" ]
                                            [ mask [ id "__3bBWeS0__mask-12", fill "white" ]
                                                [ use [ xlinkHref "#__3bBWeS0__path-11" ]
                                                    []
                                                ]
                                            , g [ id "__3bBWeS0__Surface" ]
                                                []
                                            ]
                                        ]
                                    ]
                                , g [ id "__3bBWeS0__List-/-Single-Line-/-Text-/-Body-2", stroke "none", fill "none", Svg.Attributes.mask "url(#__3bBWeS0__mask-7)" ]
                                    [ g [ transform "translate(-6.400000, 6.400000)" ]
                                        [ g [ id "__3bBWeS0__?-/-Text-/-Body-2-/-Selected-/-On-Surface-/-High-Emphasis-/-Left", transform "translate(12.800000, 4.631579)", fillOpacity "0.87", fontFamily "Roboto-Regular, Roboto", fontSize "11.2", fontWeight "normal", letterSpacing "0.2" ]
                                            [ text_ [ id "__3bBWeS0__Body-2", fill "#000000" ]
                                                [ tspan [ x "0", y "10" ]
                                                    [ text "Menu 1" ]
                                                ]
                                            ]
                                        , g [ id "__3bBWeS0__List-/-State-/-Resting" ]
                                            [ mask [ id "__3bBWeS0__mask-14", fill "white" ]
                                                [ use [ xlinkHref "#__3bBWeS0__path-13" ]
                                                    []
                                                ]
                                            , g [ id "__3bBWeS0__Surface" ]
                                                []
                                            ]
                                        ]
                                    ]
                                , g [ id "__3bBWeS0__List-/-Single-Line-/-Text-/-Body-2", stroke "none", fill "none", Svg.Attributes.mask "url(#__3bBWeS0__mask-7)" ]
                                    [ g [ transform "translate(-6.400000, 83.200000)" ]
                                        [ g [ id "__3bBWeS0__?-/-Text-/-Body-2-/-Selected-/-On-Surface-/-High-Emphasis-/-Left", transform "translate(12.800000, 4.631579)", fillOpacity "0.87", fontFamily "Roboto-Regular, Roboto", fontSize "11.2", fontWeight "normal", letterSpacing "0.2" ]
                                            [ text_ [ id "__3bBWeS0__Body-2", fill "#000000" ]
                                                [ tspan [ x "0", y "10" ]
                                                    [ text "Menu 4" ]
                                                ]
                                            ]
                                        , g [ id "__3bBWeS0__List-/-State-/-Resting" ]
                                            [ mask [ id "__3bBWeS0__mask-16", fill "white" ]
                                                [ use [ xlinkHref "#__3bBWeS0__path-15" ]
                                                    []
                                                ]
                                            , g [ id "__3bBWeS0__Surface" ]
                                                []
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        , g [ id "__3bBWeS0__List-/-Single-Line-/-Text-/-Body-2", stroke "none", fill "none", Svg.Attributes.mask "url(#__3bBWeS0__mask-4)" ]
                            [ g [ transform "translate(-6.400000, 6.400000)" ]
                                [ g [ id "__3bBWeS0__Icon-/-Arrow-Drop-Down-/-Fill", transform "translate(83.000000, 3.536842)" ]
                                    [ mask [ id "__3bBWeS0__mask-18", fill "white" ]
                                        [ use [ xlinkHref "#__3bBWeS0__path-17" ]
                                            []
                                        ]
                                    , g [ id "__3bBWeS0__Mask", fillRule "nonzero", transform "translate(9.600000, 10.000000) rotate(90.000000) translate(-9.600000, -10.000000) " ]
                                        []
                                    , g [ id "__3bBWeS0__?-/-Color-/-Icons-/-Black-/-Inactive", Svg.Attributes.mask "url(#__3bBWeS0__mask-18)", fill "#000000", fillRule "evenodd", opacity "0.54" ]
                                        [ rect [ id "__3bBWeS0__Rectangle", x "0", y "0", width "18.9530864", height "18.9530864" ]
                                            []
                                        ]
                                    ]
                                , g [ id "__3bBWeS0__?-/-Text-/-Body-2-/-Selected-/-On-Surface-/-High-Emphasis-/-Left", transform "translate(12.800000, 4.631579)", fillOpacity "0.87", fontFamily "Roboto-Regular, Roboto", fontSize "11.2", fontWeight "normal", letterSpacing "0.2" ]
                                    [ text_ [ id "__3bBWeS0__Body-2", fill "#000000" ]
                                        [ tspan [ x "0", y "10" ]
                                            [ text "Menu" ]
                                        ]
                                    ]
                                , g [ id "__3bBWeS0__List-/-State-/-Resting" ]
                                    [ mask [ id "__3bBWeS0__mask-20", fill "white" ]
                                        [ use [ xlinkHref "#__3bBWeS0__path-19" ]
                                            []
                                        ]
                                    , g [ id "__3bBWeS0__Surface" ]
                                        []
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
