module Demo.Startpage.Svg.Switch exposing (view)

import Html exposing (Html)
import Svg exposing (defs, desc, feColorMatrix, feGaussianBlur, feMerge, feMergeNode, feOffset, filter, g, mask, path, rect, svg, text, title, use)
import Svg.Attributes exposing (d, dx, dy, fill, fillOpacity, fillRule, filterUnits, height, id, in_, opacity, result, rx, stdDeviation, stroke, strokeWidth, transform, type_, values, version, viewBox, width, x, xlinkHref, y)


view : Html msg
view =
    svg [ viewBox "0 0 180 180", version "1.1" ]
        [ title []
            [ text "switch_180px" ]
        , desc []
            [ text "Created with Sketch." ]
        , defs []
            [ rect [ id "__3fH9oie__path-1", x "0", y "0", width "180", height "180" ]
                []
            , rect [ id "__3fH9oie__path-3", x "3", y "5", width "34", height "14", rx "7" ]
                []
            , rect [ id "__3fH9oie__path-5", x "-7.63833441e-14", y "0", width "20", height "20", rx "10" ]
                []
            , filter [ x "-45.0%", y "-30.0%", width "190.0%", height "190.0%", filterUnits "objectBoundingBox", id "__3fH9oie__filter-7" ]
                [ feOffset [ dx "0", dy "1", in_ "SourceAlpha", result "shadowOffsetOuter1" ]
                    []
                , feGaussianBlur [ stdDeviation "1.5", in_ "shadowOffsetOuter1", result "shadowBlurOuter1" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.2 0", type_ "matrix", in_ "shadowBlurOuter1", result "shadowMatrixOuter1" ]
                    []
                , feOffset [ dx "0", dy "2", in_ "SourceAlpha", result "shadowOffsetOuter2" ]
                    []
                , feGaussianBlur [ stdDeviation "1", in_ "shadowOffsetOuter2", result "shadowBlurOuter2" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.12 0", type_ "matrix", in_ "shadowBlurOuter2", result "shadowMatrixOuter2" ]
                    []
                , feOffset [ dx "0", dy "0", in_ "SourceAlpha", result "shadowOffsetOuter3" ]
                    []
                , feGaussianBlur [ stdDeviation "1", in_ "shadowOffsetOuter3", result "shadowBlurOuter3" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.14 0", type_ "matrix", in_ "shadowBlurOuter3", result "shadowMatrixOuter3" ]
                    []
                , feMerge []
                    [ feMergeNode [ in_ "shadowMatrixOuter1" ]
                        []
                    , feMergeNode [ in_ "shadowMatrixOuter2" ]
                        []
                    , feMergeNode [ in_ "shadowMatrixOuter3" ]
                        []
                    ]
                ]
            , rect [ id "__3fH9oie__path-8", x "3", y "5", width "34", height "14", rx "7" ]
                []
            , rect [ id "__3fH9oie__path-10", x "-7.63833441e-14", y "0", width "20", height "20", rx "10" ]
                []
            , filter [ x "-45.0%", y "-30.0%", width "190.0%", height "190.0%", filterUnits "objectBoundingBox", id "__3fH9oie__filter-12" ]
                [ feOffset [ dx "0", dy "1", in_ "SourceAlpha", result "shadowOffsetOuter1" ]
                    []
                , feGaussianBlur [ stdDeviation "1.5", in_ "shadowOffsetOuter1", result "shadowBlurOuter1" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.2 0", type_ "matrix", in_ "shadowBlurOuter1", result "shadowMatrixOuter1" ]
                    []
                , feOffset [ dx "0", dy "2", in_ "SourceAlpha", result "shadowOffsetOuter2" ]
                    []
                , feGaussianBlur [ stdDeviation "1", in_ "shadowOffsetOuter2", result "shadowBlurOuter2" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.12 0", type_ "matrix", in_ "shadowBlurOuter2", result "shadowMatrixOuter2" ]
                    []
                , feOffset [ dx "0", dy "0", in_ "SourceAlpha", result "shadowOffsetOuter3" ]
                    []
                , feGaussianBlur [ stdDeviation "1", in_ "shadowOffsetOuter3", result "shadowBlurOuter3" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.14 0", type_ "matrix", in_ "shadowBlurOuter3", result "shadowMatrixOuter3" ]
                    []
                , feMerge []
                    [ feMergeNode [ in_ "shadowMatrixOuter1" ]
                        []
                    , feMergeNode [ in_ "shadowMatrixOuter2" ]
                        []
                    , feMergeNode [ in_ "shadowMatrixOuter3" ]
                        []
                    ]
                ]
            , path [ d "M12,2 C6.48,2 2,6.48 2,12 C2,17.52 6.48,22 12,22 C17.52,22 22,17.52 22,12 C22,6.48 17.52,2 12,2 Z M12,20 C7.58,20 4,16.42 4,12 C4,7.58 7.58,4 12,4 C16.42,4 20,7.58 20,12 C20,16.42 16.42,20 12,20 Z M12,17 C14.7614237,17 17,14.7614237 17,12 C17,9.23857625 14.7614237,7 12,7 C9.23857625,7 7,9.23857625 7,12 C7,14.7614237 9.23857625,17 12,17 Z", id "__3fH9oie__path-13" ]
                []
            , path [ d "M12,2 C6.48,2 2,6.48 2,12 C2,17.52 6.48,22 12,22 C17.52,22 22,17.52 22,12 C22,6.48 17.52,2 12,2 Z M12,20 C7.58,20 4,16.42 4,12 C4,7.58 7.58,4 12,4 C16.42,4 20,7.58 20,12 C20,16.42 16.42,20 12,20 Z", id "__3fH9oie__path-15" ]
                []
            , path [ d "M19,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.11,21 21,20.1 21,19 L21,5 C21,3.9 20.11,3 19,3 Z M10,17 L5,12 L6.41,10.59 L10,14.17 L17.59,6.58 L19,8 L10,17 Z", id "__3fH9oie__path-17" ]
                []
            , path [ d "M19,5 L19,19 L5,19 L5,5 L19,5 Z M19,3 L5,3 C3.9,3 3,3.9 3,5 L3,19 C3,20.1 3.9,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,5 C21,3.9 20.1,3 19,3 Z", id "__3fH9oie__path-19" ]
                []
            ]
        , g [ id "__3fH9oie__switch_180px", stroke "none", strokeWidth "1", fill "none", fillRule "evenodd" ]
            [ g [ id "__3fH9oie__Group" ]
                [ mask [ id "__3fH9oie__mask-2", fill "white" ]
                    [ use [ xlinkHref "#__3fH9oie__path-1" ]
                        []
                    ]
                , use [ id "__3fH9oie__Mask", fill "#FAFAFA", xlinkHref "#__3fH9oie__path-1" ]
                    []
                , g [ id "__3fH9oie__Selection-Control-/-Switch-/-On-/-Enabled", Svg.Attributes.mask "url(#__3fH9oie__mask-2)" ]
                    [ g [ transform "translate(70.000000, 50.000000)" ]
                        [ g [ id "__3fH9oie__Selection-Control-/-Switch-/-Elements-/-Track" ]
                            [ mask [ id "__3fH9oie__mask-4", fill "white" ]
                                [ use [ xlinkHref "#__3fH9oie__path-3" ]
                                    []
                                ]
                            , use [ id "__3fH9oie__Surface", fill "#FAFAFA", fillRule "evenodd", xlinkHref "#__3fH9oie__path-3" ]
                                []
                            , g [ id "__3fH9oie__?-/-Color-/-Icons-/-Black-/-Active", opacity "0.379999995", Svg.Attributes.mask "url(#__3fH9oie__mask-4)", fill "#000000", fillRule "evenodd" ]
                                [ rect [ id "__3fH9oie__Rectangle-13", opacity "0.87", x "0", y "0", width "40", height "24" ]
                                    []
                                ]
                            ]
                        , g [ id "__3fH9oie__Selection-Control-/-Switch-/-Elements-/-Thumb", transform "translate(18.000000, 2.000000)" ]
                            [ mask [ id "__3fH9oie__mask-6", fill "white" ]
                                [ use [ xlinkHref "#__3fH9oie__path-5" ]
                                    []
                                ]
                            , g [ id "__3fH9oie__Surface" ]
                                [ use [ fill "black", fillOpacity "1", Svg.Attributes.filter "url(#__3fH9oie__filter-7)", xlinkHref "#__3fH9oie__path-5" ]
                                    []
                                , use [ fill "#FAFAFA", fillRule "evenodd", xlinkHref "#__3fH9oie__path-5" ]
                                    []
                                ]
                            , g [ id "__3fH9oie__?-/-Color-/-Icons-/-Black-/-Active", Svg.Attributes.mask "url(#__3fH9oie__mask-6)", fill "#000000", fillRule "evenodd", opacity "0.87" ]
                                [ rect [ id "__3fH9oie__Rectangle-13", x "0", y "0", width "20", height "20" ]
                                    []
                                ]
                            ]
                        ]
                    ]
                , g [ id "__3fH9oie__Selection-Control-/-Switch-/-Off-/-Enabled", Svg.Attributes.mask "url(#__3fH9oie__mask-2)" ]
                    [ g [ transform "translate(70.000000, 106.000000)" ]
                        [ g [ id "__3fH9oie__Selection-Control-/-Switch-/-Elements-/-Track" ]
                            [ mask [ id "__3fH9oie__mask-9", fill "white" ]
                                [ use [ xlinkHref "#__3fH9oie__path-8" ]
                                    []
                                ]
                            , use [ id "__3fH9oie__Surface", fill "#FAFAFA", fillRule "evenodd", xlinkHref "#__3fH9oie__path-8" ]
                                []
                            , g [ id "__3fH9oie__?-/-Color-/-Icons-/-Black-/-Inactive", opacity "0.379999995", Svg.Attributes.mask "url(#__3fH9oie__mask-9)", fill "#000000", fillRule "evenodd" ]
                                [ rect [ id "__3fH9oie__Rectangle", opacity "0.54", x "0", y "0", width "40", height "24" ]
                                    []
                                ]
                            ]
                        , g [ id "__3fH9oie__Selection-Control-/-Switch-/-Elements-/-Thumb", transform "translate(2.000000, 2.000000)" ]
                            [ mask [ id "__3fH9oie__mask-11", fill "white" ]
                                [ use [ xlinkHref "#__3fH9oie__path-10" ]
                                    []
                                ]
                            , g [ id "__3fH9oie__Surface" ]
                                [ use [ fill "black", fillOpacity "1", Svg.Attributes.filter "url(#__3fH9oie__filter-12)", xlinkHref "#__3fH9oie__path-10" ]
                                    []
                                , use [ fill "#FAFAFA", fillRule "evenodd", xlinkHref "#__3fH9oie__path-10" ]
                                    []
                                ]
                            , g [ id "__3fH9oie__?-/-Color-/-Surface-/-Light", Svg.Attributes.mask "url(#__3fH9oie__mask-11)", fill "#FAFAFA", fillRule "evenodd" ]
                                [ rect [ id "__3fH9oie__Rectangle-13", x "0", y "0", width "20", height "20" ]
                                    []
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
