module Demo.Startpage.Svg.Tabs exposing (view)

import Html exposing (Html)
import Svg exposing (defs, desc, feColorMatrix, feGaussianBlur, feMerge, feMergeNode, feOffset, filter, g, mask, rect, svg, text, text_, title, tspan, use)
import Svg.Attributes exposing (dx, dy, fill, fillOpacity, fillRule, filterUnits, fontFamily, fontSize, fontWeight, height, id, in_, letterSpacing, result, stdDeviation, stroke, strokeWidth, transform, type_, values, version, viewBox, width, x, xlinkHref, y)


view : Html msg
view =
    svg [ viewBox "0 0 180 180", version "1.1" ]
        [ title []
            [ text "tabs_180px" ]
        , desc []
            [ text "Created with Sketch." ]
        , defs []
            [ rect [ id "__2TYoTZ5__path-1", x "0", y "0", width "180", height "180" ]
                []
            , rect [ id "__2TYoTZ5__path-3", x "0", y "0", width "288", height "38.4" ]
                []
            , filter [ x "-6.8%", y "-35.2%", width "113.5%", height "201.6%", filterUnits "objectBoundingBox", id "__2TYoTZ5__filter-5" ]
                [ feOffset [ dx "0", dy "1", in_ "SourceAlpha", result "shadowOffsetOuter1" ]
                    []
                , feGaussianBlur [ stdDeviation "4", in_ "shadowOffsetOuter1", result "shadowBlurOuter1" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.2 0", type_ "matrix", in_ "shadowBlurOuter1", result "shadowMatrixOuter1" ]
                    []
                , feOffset [ dx "0", dy "3", in_ "SourceAlpha", result "shadowOffsetOuter2" ]
                    []
                , feGaussianBlur [ stdDeviation "2", in_ "shadowOffsetOuter2", result "shadowBlurOuter2" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.12 0", type_ "matrix", in_ "shadowBlurOuter2", result "shadowMatrixOuter2" ]
                    []
                , feOffset [ dx "0", dy "2", in_ "SourceAlpha", result "shadowOffsetOuter3" ]
                    []
                , feGaussianBlur [ stdDeviation "1.5", in_ "shadowOffsetOuter3", result "shadowBlurOuter3" ]
                    []
                , feColorMatrix [ values "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.14 0", type_ "matrix", in_ "shadowBlurOuter3", result "shadowMatrixOuter3" ]
                    []
                , feMerge []
                    [ feMergeNode [ in_ "shadowMatrixOuter1" ]
                        []
                    , feMergeNode [ in_ "shadowMatrixOuter2" ]
                        []
                    , feMergeNode [ in_ "shadowMatrixOuter3" ]
                        []
                    ]
                ]
            , rect [ id "__2TYoTZ5__path-6", x "0", y "0", width "96", height "38.4" ]
                []
            , rect [ id "__2TYoTZ5__path-8", x "0", y "0", width "96", height "38.4" ]
                []
            , rect [ id "__2TYoTZ5__path-10", x "0", y "0", width "96", height "38.4" ]
                []
            ]
        , g [ id "__2TYoTZ5__tabs_180px", stroke "none", strokeWidth "1", fill "none", fillRule "evenodd" ]
            [ g [ id "__2TYoTZ5__Group-+-Tab-/-Text-Tab-/-Raised-Mask" ]
                [ mask [ id "__2TYoTZ5__mask-2", fill "white" ]
                    [ use [ xlinkHref "#__2TYoTZ5__path-1" ]
                        []
                    ]
                , g [ id "__2TYoTZ5__Mask" ]
                    []
                , g [ id "__2TYoTZ5__Group", Svg.Attributes.mask "url(#__2TYoTZ5__mask-2)", fill "#F5F5F5" ]
                    [ g [ transform "translate(0.000000, 40.000000)", id "__2TYoTZ5__Rectangle" ]
                        [ rect [ x "0", y "0", width "225", height "166" ]
                            []
                        ]
                    ]
                , g [ id "__2TYoTZ5__Tab-/-Fixed-Tabs-/-Text-Labels-Only-/-Raised", Svg.Attributes.mask "url(#__2TYoTZ5__mask-2)" ]
                    [ g [ transform "translate(0.000000, 30.000000)" ]
                        [ mask [ id "__2TYoTZ5__mask-4", fill "white" ]
                            [ use [ xlinkHref "#__2TYoTZ5__path-3" ]
                                []
                            ]
                        , g [ id "__2TYoTZ5__Surface", stroke "none", fill "none" ]
                            [ use [ fill "black", fillOpacity "1", Svg.Attributes.filter "url(#__2TYoTZ5__filter-5)", xlinkHref "#__2TYoTZ5__path-3" ]
                                []
                            , use [ fill "#FAFAFA", fillRule "evenodd", xlinkHref "#__2TYoTZ5__path-3" ]
                                []
                            ]
                        , g [ id "__2TYoTZ5__?-/-Color-/-Surface-/-Primary-or-Secondary", stroke "none", fill "none", Svg.Attributes.mask "url(#__2TYoTZ5__mask-4)", fillRule "evenodd" ]
                            [ g [ id "__2TYoTZ5__?-/-Color-/-Primary-/-500", fill "#212121" ]
                                [ rect [ id "__2TYoTZ5__Rectangle-13", x "0", y "0", width "288", height "38" ]
                                    []
                                ]
                            ]
                        , g [ id "__2TYoTZ5__Tab-/-Elements-/-Text-Tab-/-Inactive-/-Enabled", stroke "none", fill "none", Svg.Attributes.mask "url(#__2TYoTZ5__mask-4)" ]
                            [ g [ transform "translate(192.000000, 0.000000)" ]
                                [ mask [ id "__2TYoTZ5__mask-7", fill "white" ]
                                    [ use [ xlinkHref "#__2TYoTZ5__path-6" ]
                                        []
                                    ]
                                , g [ id "__2TYoTZ5__Surface", stroke "none", fill "none" ]
                                    []
                                , g [ id "__2TYoTZ5__?-/-Text-/-Button-/-White-/-High-Emphasis-/-Center", stroke "none", fill "none", Svg.Attributes.mask "url(#__2TYoTZ5__mask-7)", fontFamily "Roboto-Medium, Roboto", fontSize "11.2", fontWeight "400", letterSpacing "1" ]
                                    [ g [ transform "translate(0.000000, 12.800000)", id "__2TYoTZ5__Button" ]
                                        [ text_ []
                                            [ tspan [ x "25.825", y "7.97109375", fill "#FFFFFF" ]
                                                [ text "TAB" ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        , g [ id "__2TYoTZ5__Tab-/-Elements-/-Text-Tab-/-Inactive-/-Enabled", stroke "none", fill "none", Svg.Attributes.mask "url(#__2TYoTZ5__mask-4)" ]
                            [ g [ transform "translate(96.000000, 0.000000)" ]
                                [ mask [ id "__2TYoTZ5__mask-9", fill "white" ]
                                    [ use [ xlinkHref "#__2TYoTZ5__path-8" ]
                                        []
                                    ]
                                , g [ id "__2TYoTZ5__Surface", stroke "none", fill "none" ]
                                    []
                                , g [ id "__2TYoTZ5__?-/-Text-/-Button-/-White-/-High-Emphasis-/-Center", stroke "none", fill "none", Svg.Attributes.mask "url(#__2TYoTZ5__mask-9)", fontFamily "Roboto-Medium, Roboto", fontSize "11.2", fontWeight "400", letterSpacing "1" ]
                                    [ g [ transform "translate(0.000000, 12.800000)", id "__2TYoTZ5__Button" ]
                                        [ text_ []
                                            [ tspan [ x "25.825", y "7.97109375", fill "#FFFFFF" ]
                                                [ text "TAB" ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        , g [ id "__2TYoTZ5__Tab-/-Elements-/-Text-Tab-/-Active-/-Enabled", stroke "none", fill "none", Svg.Attributes.mask "url(#__2TYoTZ5__mask-4)" ]
                            [ mask [ id "__2TYoTZ5__mask-11", fill "white" ]
                                [ use [ xlinkHref "#__2TYoTZ5__path-10" ]
                                    []
                                ]
                            , g [ id "__2TYoTZ5__Surface" ]
                                []
                            , g [ id "__2TYoTZ5__Tab-/-Elements-/-Indicator", Svg.Attributes.mask "url(#__2TYoTZ5__mask-11)", fill "#FFFFFF", fillRule "evenodd" ]
                                [ g [ id "__2TYoTZ5__?-/-Color-/-Surface-/-Base", transform "translate(0.000000, 36.000000)" ]
                                    [ rect [ id "__2TYoTZ5__Rectangle-13", x "0", y "0", width "96", height "2" ]
                                        []
                                    ]
                                ]
                            , g [ id "__2TYoTZ5__?-/-Text-/-Button-/-White-/-High-Emphasis-/-Center", Svg.Attributes.mask "url(#__2TYoTZ5__mask-11)", fontFamily "Roboto-Medium, Roboto", fontSize "11.2", fontWeight "400", letterSpacing "1" ]
                                [ g [ transform "translate(0.000000, 12.800000)", id "__2TYoTZ5__Button" ]
                                    [ text_ []
                                        [ tspan [ x "8.24492187", y "7.97109375", fill "#FFFFFF" ]
                                            [ text "ITEM ONE" ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
