module Demo.Startpage.Svg.TopAppBar exposing (view)

import Html exposing (Html)
import Svg exposing (defs, desc, g, mask, path, rect, svg, text, text_, title, tspan, use)
import Svg.Attributes exposing (d, fill, fillRule, fontFamily, fontSize, fontWeight, height, id, letterSpacing, stroke, strokeWidth, transform, version, viewBox, width, x, xlinkHref, y)


view : Html msg
view =
    svg [ viewBox "0 0 180 180", version "1.1" ]
        [ title []
            [ text "top_app_bar_180px" ]
        , desc []
            [ text "Created with Sketch." ]
        , defs []
            [ rect [ id "__38Y2TWt__path-1", x "0", y "0", width "180", height "180" ]
                []
            , rect [ id "__38Y2TWt__path-3", x "0", y "0", width "288", height "102" ]
                []
            , path [ d "M2.4,14.4 L16.8,14.4 L16.8,12.8 L2.4,12.8 L2.4,14.4 Z M2.4,10.4 L16.8,10.4 L16.8,8.8 L2.4,8.8 L2.4,10.4 Z M2.4,4.8 L2.4,6.4 L16.8,6.4 L16.8,4.8 L2.4,4.8 Z", id "__38Y2TWt__path-5" ]
                []
            ]
        , g [ id "__38Y2TWt__top_app_bar_180px", stroke "none", strokeWidth "1", fill "none", fillRule "evenodd" ]
            [ mask [ id "__38Y2TWt__mask-2", fill "white" ]
                [ use [ xlinkHref "#__38Y2TWt__path-1" ]
                    []
                ]
            , use [ id "__38Y2TWt__Mask", fill "#FAFAFA", xlinkHref "#__38Y2TWt__path-1" ]
                []
            , g [ id "__38Y2TWt__Dialog-/-Header-Copy-2", Svg.Attributes.mask "url(#__38Y2TWt__mask-2)" ]
                [ g [ transform "translate(30.000000, 0.000000)", id "__38Y2TWt__Group-3" ]
                    [ g []
                        [ rect [ id "__38Y2TWt__Rectangle", fill "#F5F5F5", x "0", y "0", width "150", height "188" ]
                            []
                        , g [ id "__38Y2TWt__App-Bar-/-Top-/-Extended-/-Flat" ]
                            [ mask [ id "__38Y2TWt__mask-4", fill "white" ]
                                [ use [ xlinkHref "#__38Y2TWt__path-3" ]
                                    []
                                ]
                            , use [ id "__38Y2TWt__Surface", fill "#FAFAFA", xlinkHref "#__38Y2TWt__path-3" ]
                                []
                            , g [ id "__38Y2TWt__?-/-Color-/-Primary-/-Main", Svg.Attributes.mask "url(#__38Y2TWt__mask-4)", fill "#212121" ]
                                [ g [ id "__38Y2TWt__?-/-Color-/-Primary-/-900" ]
                                    [ g []
                                        [ rect [ id "__38Y2TWt__Rectangle-13", x "0", y "0", width "288", height "102" ]
                                            []
                                        ]
                                    ]
                                ]
                            , g [ id "__38Y2TWt__Text-/-H6-/-P---Dark-/-Left", Svg.Attributes.mask "url(#__38Y2TWt__mask-4)", fontFamily "Roboto-Medium, Roboto", fontSize "16", fontWeight "400", letterSpacing "0.120000005" ]
                                [ g [ transform "translate(47.000000, 66.000000)", id "__38Y2TWt__Headline-6" ]
                                    [ text_ []
                                        [ tspan [ x "0", y "15", fill "#FFFFFF" ]
                                            [ text "Top App Bar" ]
                                        ]
                                    ]
                                ]
                            , g [ id "__38Y2TWt__Icons-", Svg.Attributes.mask "url(#__38Y2TWt__mask-4)" ]
                                [ g [ transform "translate(12.800000, 12.750000)", id "__38Y2TWt__Icon-1" ]
                                    [ g []
                                        [ g [ id "__38Y2TWt__Icon-/-Menu-/-Fill" ]
                                            [ mask [ id "__38Y2TWt__mask-6", fill "white" ]
                                                [ use [ xlinkHref "#__38Y2TWt__path-5" ]
                                                    []
                                                ]
                                            , g [ id "__38Y2TWt__Mask", fillRule "nonzero" ]
                                                []
                                            , g [ id "__38Y2TWt__?-/-Color-/-Icons-/-White-/-100%", Svg.Attributes.mask "url(#__38Y2TWt__mask-6)", fill "#FFFFFF", fillRule "evenodd" ]
                                                [ rect [ id "__38Y2TWt__Rectangle-13", x "0", y "0", width "18.9530864", height "18.9530864" ]
                                                    []
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
