#!/usr/bin/python

import sys, os
from subprocess import call

message_file = sys.argv[1]

def check_format_rules(lineno, line):
    real_lineno = lineno + 1
    if lineno == 0:
        linewarning = ""
        if len(line) > 50:
            linewarning = "Warning - line %d: Please limit the subject line to 50 characters." \
                    "in length.\n" % (real_lineno,)
        if not line[0].isupper() :
            linewarning = linewarning + "Warning - line %d: Please capitalize the subject line.\n" % (real_lineno,)
        if line.endswith('.') :
            linewarning = linewarning +  "Warning - line %d: Please do not end the subject line with a period." % (real_lineno,)
        if linewarning:
            return linewarning
    if lineno == 1:
        if line:
            return "Warning - line %d: Please separate subject from body with a blank line." % (real_lineno,)
    if not line.startswith('#'):
        if len(line) > 72:
            return "Warning - line %d: Please wrap the body at 72 characters." % (real_lineno,)
    return False


while True:
    commit_msg = list()
    errors = list()
    with open(message_file) as commit_fd:
        for lineno, line in enumerate(commit_fd):
            stripped_line = line.strip()
            commit_msg.append(line)
            e = check_format_rules(lineno, stripped_line)
            if e:
                errors.append(e)
    if errors:
        print '# Git commit message warnings:\nThese are guidelines to help us improve commit messages.'
        for error in errors:
            print '{}'.format(error)
        print 'You can run <git commit --amend> to fix this message.'
    break
